#!/usr/bin/env python3
"""
backup_nowa.py

Incremental backup of the NOWA-Engine source tree.

Copies everything recursively from the source to the target, but leaves out what can be
regenerated by a build: Visual Studio intermediate files, .obj / .pch and friends, output
directories, and version control data.

Default behaviour is an INCREMENTAL MIRROR: files are only copied when they are missing in
the target or when size or modification time differ. Running it a second time therefore
takes seconds instead of re-copying gigabytes.

What is kept on purpose
-----------------------
Project files (.sln, .vcxproj, .vcxproj.filters, CMakeLists.txt) are KEPT, because without
them the backup cannot be built again. Only the per-user files (.vcxproj.user, .suo) are
dropped. Pass --exclude-project-files if you really want the solution files gone too.

Usage
-----
    python backup_nowa.py                          # uses the configured default paths
    python backup_nowa.py --dry-run                # show what would happen, write nothing
    python backup_nowa.py --timestamp              # backup into a dated subfolder
    python backup_nowa.py --zip                    # write a single .zip archive instead
    python backup_nowa.py --delete                 # also remove target files gone from source
    python backup_nowa.py --source D:\\Other --target E:\\Backup

    python backup_nowa.py --list-excludes          # print the active exclusion rules
"""

import argparse
import fnmatch
import os
import shutil
import sys
import time
import zipfile

# ---------------------------------------------------------------------------------------
# Defaults - adjust here if the paths ever change
# ---------------------------------------------------------------------------------------

DEFAULT_SOURCE = r"C:\Users\lukas\Documents\NOWA-Engine"
DEFAULT_TARGET = r"F:\Backup"

# Directory names that are skipped completely, at any depth. Matched case insensitively
# against the directory name, not against the full path.
EXCLUDED_DIRECTORIES = [
    ".git",
    ".svn",
    ".hg",
    ".vs",              # Visual Studio per-user database and browsing files
    "ipch",             # precompiled header cache
    "Debug",
    "Release",
    "RelWithDebInfo",
    "MinSizeRel",
    "x64",
    "x86",
    "Win32",
    "CMakeFiles",
    "__pycache__",
    "node_modules",
    ".cache",
]

# File extensions that are skipped. Matched case insensitively.
EXCLUDED_EXTENSIONS = [
    ".obj",
    ".o",
    ".pch",
    ".ipch",
    ".gch",
    ".pdb",
    ".idb",
    ".ilk",
    ".exp",
    ".iobj",
    ".ipdb",
    ".tlog",
    ".res",
    ".recipe",
    ".lastbuildstate",
    ".unsuccessfulbuild",
    ".suo",
    ".sdf",
    ".opensdf",
    ".ncb",
    ".aps",
    ".vcxproj.user",
    ".db-shm",
    ".db-wal",
    ".tmp",
    ".temp",
]

# Whole file names that are skipped, matched case insensitively.
EXCLUDED_FILENAMES = [
    "thumbs.db",
    "desktop.ini",
    ".ds_store",
]

# Glob patterns matched against the file name, for things an extension cannot express.
EXCLUDED_PATTERNS = [
    "*.VC.db",
    "*.VC.opendb",
    "*.vcxproj.user",
]

# Additionally excluded only with --exclude-project-files.
PROJECT_FILE_EXTENSIONS = [
    ".sln",
    ".vcxproj",
    ".filters",
    ".props",
    ".vcproj",
]


# ---------------------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------------------

def long_path(path):
    """Return a path usable beyond the Windows 260 character limit.

    Deep engine trees plus a backup root easily exceed MAX_PATH, and the copy would then
    fail with a confusing 'file not found'. The \\\\?\\ prefix lifts that limit. On any
    other platform the path is returned unchanged.
    """
    if os.name != "nt":
        return path

    absolute = os.path.abspath(path)
    if absolute.startswith("\\\\?\\"):
        return absolute
    if absolute.startswith("\\\\"):
        return "\\\\?\\UNC\\" + absolute[2:]
    return "\\\\?\\" + absolute


def human_size(number_of_bytes):
    """Format a byte count for humans."""
    value = float(number_of_bytes)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024.0 or unit == "TB":
            return "%.1f %s" % (value, unit)
        value /= 1024.0
    return "%.1f TB" % value


# ---------------------------------------------------------------------------------------
# Exclusion rules
# ---------------------------------------------------------------------------------------

class ExclusionRules(object):
    """Holds the active exclusion rules and answers whether a path is excluded."""

    def __init__(self, args):
        self.directories = set(name.lower() for name in EXCLUDED_DIRECTORIES)
        self.extensions = set(name.lower() for name in EXCLUDED_EXTENSIONS)
        self.filenames = set(name.lower() for name in EXCLUDED_FILENAMES)
        self.patterns = list(EXCLUDED_PATTERNS)

        for name in args.keep_dir:
            self.directories.discard(name.lower())

        for name in args.exclude_dir:
            self.directories.add(name.lower())

        for extension in args.exclude_ext:
            if not extension.startswith("."):
                extension = "." + extension
            self.extensions.add(extension.lower())

        if args.exclude_project_files:
            for extension in PROJECT_FILE_EXTENSIONS:
                self.extensions.add(extension)

        self.max_size_bytes = args.max_size_mb * 1024 * 1024 if args.max_size_mb > 0 else 0

    def is_excluded_directory(self, name):
        return name.lower() in self.directories

    def is_excluded_file(self, name, size_bytes):
        lower = name.lower()

        if lower in self.filenames:
            return True

        # Compound extensions such as .vcxproj.user are not caught by splitext, so test the
        # full name against every known extension as a suffix first.
        for extension in self.extensions:
            if lower.endswith(extension):
                return True

        for pattern in self.patterns:
            if fnmatch.fnmatch(lower, pattern.lower()):
                return True

        if self.max_size_bytes > 0 and size_bytes > self.max_size_bytes:
            return True

        return False

    def describe(self):
        print("Excluded directories (%d):" % len(self.directories))
        print("  " + ", ".join(sorted(self.directories)))
        print("")
        print("Excluded extensions (%d):" % len(self.extensions))
        print("  " + ", ".join(sorted(self.extensions)))
        print("")
        print("Excluded file names (%d):" % len(self.filenames))
        print("  " + ", ".join(sorted(self.filenames)))
        print("")
        print("Excluded patterns (%d):" % len(self.patterns))
        print("  " + ", ".join(self.patterns))
        if self.max_size_bytes > 0:
            print("")
            print("Files larger than %s are skipped." % human_size(self.max_size_bytes))


# ---------------------------------------------------------------------------------------
# Scanning
# ---------------------------------------------------------------------------------------

def scan_source(source, rules, stats):
    """Walk the source tree and yield (absolute path, relative path, size) for every file
    that survives the exclusion rules."""
    for root, directories, files in os.walk(source):
        # Prune excluded directories in place, so os.walk does not even descend into them.
        kept = []
        for name in directories:
            if rules.is_excluded_directory(name):
                stats["skipped_dirs"] += 1
            else:
                kept.append(name)
        directories[:] = kept

        for name in files:
            absolute = os.path.join(root, name)
            try:
                size = os.path.getsize(long_path(absolute))
            except OSError:
                stats["errors"] += 1
                continue

            if rules.is_excluded_file(name, size):
                stats["skipped_files"] += 1
                stats["skipped_bytes"] += size
                continue

            relative = os.path.relpath(absolute, source)
            yield absolute, relative, size


def needs_copy(source_file, target_file, tolerance_seconds):
    """Decide whether a file has to be copied.

    Compares size and modification time. FAT and NTFS store timestamps with different
    resolution, so a small tolerance avoids copying everything again when the backup drive
    uses another file system.
    """
    try:
        target_stat = os.stat(long_path(target_file))
    except OSError:
        return True

    try:
        source_stat = os.stat(long_path(source_file))
    except OSError:
        return True

    if source_stat.st_size != target_stat.st_size:
        return True

    if abs(source_stat.st_mtime - target_stat.st_mtime) > tolerance_seconds:
        return True

    return False


# ---------------------------------------------------------------------------------------
# Backup modes
# ---------------------------------------------------------------------------------------

def backup_to_directory(source, target, rules, args, stats):
    """Incremental copy of the source tree into the target directory."""
    copied_relative_paths = set()

    for absolute, relative, size in scan_source(source, rules, stats):
        target_file = os.path.join(target, relative)
        copied_relative_paths.add(relative.lower())

        stats["considered"] += 1
        stats["considered_bytes"] += size

        if False == args.force and False == needs_copy(absolute, target_file, args.time_tolerance):
            stats["unchanged"] += 1
            if args.verbose:
                print("  unchanged  %s" % relative)
            continue

        if args.dry_run:
            print("  would copy %s  (%s)" % (relative, human_size(size)))
            stats["copied"] += 1
            stats["copied_bytes"] += size
            continue

        target_directory = os.path.dirname(target_file)
        if target_directory:
            try:
                os.makedirs(long_path(target_directory), exist_ok=True)
            except OSError as error:
                print("  ERROR      cannot create %s: %s" % (target_directory, error))
                stats["errors"] += 1
                continue

        try:
            # copy2 preserves the modification time, which is what makes the incremental
            # comparison above work on the next run.
            shutil.copy2(long_path(absolute), long_path(target_file))
            stats["copied"] += 1
            stats["copied_bytes"] += size
            if args.verbose:
                print("  copied     %s  (%s)" % (relative, human_size(size)))
        except (OSError, shutil.Error) as error:
            print("  ERROR      %s: %s" % (relative, error))
            stats["errors"] += 1

    if args.delete:
        remove_orphans(target, copied_relative_paths, args, stats)


def remove_orphans(target, keep_relative_paths, args, stats):
    """Remove files in the target that no longer exist in the source.

    Only reachable via --delete, because a wrong source path plus this flag would otherwise
    wipe a good backup.
    """
    if not os.path.isdir(target):
        return

    for root, _directories, files in os.walk(target, topdown=False):
        for name in files:
            absolute = os.path.join(root, name)
            relative = os.path.relpath(absolute, target)
            if relative.lower() in keep_relative_paths:
                continue

            if args.dry_run:
                print("  would delete %s" % relative)
                stats["deleted"] += 1
                continue

            try:
                os.remove(long_path(absolute))
                stats["deleted"] += 1
                if args.verbose:
                    print("  deleted    %s" % relative)
            except OSError as error:
                print("  ERROR      cannot delete %s: %s" % (relative, error))
                stats["errors"] += 1

        # Clean up directories that are empty after the removals.
        try:
            if not os.listdir(long_path(root)) and os.path.abspath(root) != os.path.abspath(target):
                if not args.dry_run:
                    os.rmdir(long_path(root))
        except OSError:
            pass


def backup_to_zip(source, archive_path, rules, args, stats):
    """Write the whole filtered tree into a single zip archive."""
    if args.dry_run:
        for _absolute, relative, size in scan_source(source, rules, stats):
            stats["considered"] += 1
            stats["considered_bytes"] += size
            stats["copied"] += 1
            stats["copied_bytes"] += size
            if args.verbose:
                print("  would add  %s  (%s)" % (relative, human_size(size)))
        print("  would write archive: %s" % archive_path)
        return

    archive_directory = os.path.dirname(archive_path)
    if archive_directory:
        os.makedirs(long_path(archive_directory), exist_ok=True)

    compression = zipfile.ZIP_DEFLATED if args.compress else zipfile.ZIP_STORED

    with zipfile.ZipFile(archive_path, "w", compression, allowZip64=True) as archive:
        for absolute, relative, size in scan_source(source, rules, stats):
            stats["considered"] += 1
            stats["considered_bytes"] += size
            try:
                archive.write(long_path(absolute), relative)
                stats["copied"] += 1
                stats["copied_bytes"] += size
                if args.verbose:
                    print("  added      %s  (%s)" % (relative, human_size(size)))
            except (OSError, ValueError) as error:
                print("  ERROR      %s: %s" % (relative, error))
                stats["errors"] += 1


# ---------------------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Incremental backup of the NOWA-Engine source tree, without build artifacts.")
    parser.add_argument("--source", default=DEFAULT_SOURCE, help="source directory (default: %s)" % DEFAULT_SOURCE)
    parser.add_argument("--target", default=DEFAULT_TARGET, help="target directory (default: %s)" % DEFAULT_TARGET)

    parser.add_argument("--timestamp", action="store_true", help="back up into a dated subfolder instead of mirroring")
    parser.add_argument("--zip", dest="make_zip", action="store_true", help="write a single zip archive instead of a directory")
    parser.add_argument("--compress", action="store_true", help="with --zip, deflate instead of store (slower, smaller)")

    parser.add_argument("--dry-run", action="store_true", help="show what would happen, write nothing")
    parser.add_argument("--verbose", action="store_true", help="list every file, not just the summary")
    parser.add_argument("--force", action="store_true", help="copy every file even if it looks unchanged")
    parser.add_argument("--delete", action="store_true", help="remove target files that no longer exist in the source")

    parser.add_argument("--exclude-dir", action="append", default=[], metavar="NAME", help="additional directory name to skip (repeatable)")
    parser.add_argument("--keep-dir", action="append", default=[], metavar="NAME", help="directory name to KEEP although it is excluded by default (repeatable)")
    parser.add_argument("--exclude-ext", action="append", default=[], metavar="EXT", help="additional file extension to skip (repeatable)")
    parser.add_argument("--exclude-project-files", action="store_true", help="also skip .sln / .vcxproj / .props files")
    parser.add_argument("--max-size-mb", type=int, default=0, help="skip files larger than this many MB (0 = no limit)")

    parser.add_argument("--time-tolerance", type=float, default=2.0, help="modification time difference in seconds still counted as equal (default 2.0)")
    parser.add_argument("--list-excludes", action="store_true", help="print the active exclusion rules and exit")

    args = parser.parse_args()

    rules = ExclusionRules(args)

    if args.list_excludes:
        rules.describe()
        return 0

    source = os.path.abspath(args.source)
    if not os.path.isdir(long_path(source)):
        sys.exit("Source directory does not exist: %s" % source)

    project_name = os.path.basename(source.rstrip("\\/")) or "backup"
    stamp = time.strftime("%Y-%m-%d_%H%M")

    if args.make_zip:
        destination = os.path.join(os.path.abspath(args.target), "%s_%s.zip" % (project_name, stamp))
    elif args.timestamp:
        destination = os.path.join(os.path.abspath(args.target), "%s_%s" % (project_name, stamp))
    else:
        destination = os.path.join(os.path.abspath(args.target), project_name)

    # Refuse to write the backup into the tree that is being backed up - that would recurse
    # into itself and fill the disk.
    if not args.make_zip:
        normalized_source = os.path.normcase(os.path.abspath(source))
        normalized_target = os.path.normcase(os.path.abspath(destination))
        if normalized_target.startswith(normalized_source + os.sep) or normalized_target == normalized_source:
            sys.exit("Target lies inside the source directory. Choose a target outside of: %s" % source)

    print("Source:      %s" % source)
    print("Destination: %s" % destination)
    print("Mode:        %s" % ("zip archive" if args.make_zip else ("timestamped copy" if args.timestamp else "incremental mirror")))
    if args.delete:
        print("             --delete is active: target files missing in the source will be removed")
    if args.dry_run:
        print("DRY RUN - nothing will be written")
    print("")

    stats = {
        "considered": 0, "considered_bytes": 0,
        "copied": 0, "copied_bytes": 0,
        "unchanged": 0,
        "skipped_files": 0, "skipped_bytes": 0, "skipped_dirs": 0,
        "deleted": 0, "errors": 0,
    }

    started = time.time()

    if args.make_zip:
        backup_to_zip(source, destination, rules, args, stats)
    else:
        backup_to_directory(source, destination, rules, args, stats)

    elapsed = time.time() - started

    print("")
    print("-" * 72)
    print("Files considered : %d  (%s)" % (stats["considered"], human_size(stats["considered_bytes"])))
    print("Copied           : %d  (%s)" % (stats["copied"], human_size(stats["copied_bytes"])))
    print("Unchanged        : %d" % stats["unchanged"])
    print("Skipped files    : %d  (%s of build artifacts)" % (stats["skipped_files"], human_size(stats["skipped_bytes"])))
    print("Skipped dirs     : %d" % stats["skipped_dirs"])
    if args.delete:
        print("Deleted          : %d" % stats["deleted"])
    print("Errors           : %d" % stats["errors"])
    print("Elapsed          : %.1f s" % elapsed)

    if args.dry_run:
        print("")
        print("Nothing was written. Drop --dry-run to run the backup.")

    return 1 if stats["errors"] > 0 else 0


if __name__ == "__main__":
    sys.exit(main())
