copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dAnimation\Debug\dAnimation_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Debug\dContainers_d.exp" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Debug\dContainers_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Debug\dCustomJoints_d.exp" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Debug\dCustomJoints_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgCore\Debug\dgCore_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgPhysics\Debug\dgPhysics_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dMath\Debug\dMath_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dModel\Debug\dModel_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Debug\dNewton_d.exp" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Debug\dNewton_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Debug\dScene_d.exp" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Debug\dScene_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Debug\dVehicle_d.exp" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Debug\dVehicle_d.lib" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Debug\newton_d.exp" ".\bin\Debug\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Debug\newton_d.lib" ".\bin\Debug\libs"


copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dAnimation\Debug\dAnimation_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Debug\dContainers_d.dll" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Debug\dContainers_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Debug\dCustomJoints_d.dll" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Debug\dCustomJoints_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgCore\Debug\dgCore_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgPhysics\Debug\dgPhysics_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dMath\Debug\dMath_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dModel\Debug\dModel_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Debug\dNewton_d.dll" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Debug\dNewton_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Debug\dScene_d.dll" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Debug\dScene_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Debug\dVehicle_d.dll" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Debug\dVehicle_d.pdb" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Debug\newton_d.dll" ".\bin\Debug"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Debug\newton_d.pdb" ".\bin\Debug"



copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dAnimation\Release\dAnimation.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Release\dContainers.exp" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Release\dContainers.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Release\dCustomJoints.exp" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Release\dCustomJoints.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgCore\Release\dgCore.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgPhysics\Release\dgPhysics.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dMath\Release\dMath.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dModel\Release\dModel.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Release\dNewton.exp" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Release\dNewton.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Release\dScene.exp" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Release\dScene.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Release\dVehicle.exp" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Release\dVehicle.lib" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Release\newton.exp" ".\bin\Release\libs"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Release\newton.lib" ".\bin\Release\libs"


copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dAnimation\Release\dAnimation.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Release\dContainers.dll" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dContainers\Release\dContainers.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Release\dCustomJoints.dll" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dCustomJoints\Release\dCustomJoints.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgCore\Release\dgCore.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dgPhysics\Release\dgPhysics.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dMath\Release\dMath.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dModel\Release\dModel.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Release\dNewton.dll" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dNewton\Release\dNewton.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Release\dScene.dll" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dScene\Release\dScene.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Release\dVehicle.dll" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\dVehicle\Release\dVehicle.pdb" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Release\newton.dll" ".\bin\Release"
copy /b/v/y ".\external\newton-dynamics\sdk\projects\visualStudio_2015_dll\x64\newton\Release\newton.pdb" ".\bin\Release"