version: 2.3.{build}

environment:
  matrix:
#    - PLATFORM: x86
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      BUILD_SCRIPT: build_ogre_Visual_Studio_15_2017_Win32.bat
#    - PLATFORM: x86
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      BUILD_SCRIPT: build_ogre_Visual_Studio_14_2015_Win32.bat
#    - PLATFORM: x86
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      BUILD_SCRIPT: build_ogre_Visual_Studio_12_2013_Win32.bat
#    - PLATFORM: x64
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      BUILD_SCRIPT: build_ogre_Visual_Studio_15_2017_x64.bat
#    - PLATFORM: x64
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      BUILD_SCRIPT: build_ogre_Visual_Studio_14_2015_x64.bat
    - PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python36-x64"
      PYTHONHOME: "C:\\Python36-x64"
      PYTHONPATH: "C:\\Python36-x64\\lib\\site-packages"
      PATH: "C:\\Python36-x64;C:\\Python36\\Scripts;%PATH%"
      BUILD_SCRIPT: build_ci_windows.bat

cache:
  - ..\ogredeps

build_script:
  - cmd: Scripts\BuildScripts\%BUILD_SCRIPT%

